/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_govee_pad_base_lua_LuaState */

#ifndef _Included_com_govee_pad_base_lua_LuaState
#define _Included_com_govee_pad_base_lua_LuaState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_govee_pad_base_lua_LuaState
 * Method:    nativeLuaOpen
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_govee_pad_base_lua_LuaState_nativeLuaOpen
        (JNIEnv *, jobject);

/*
 * Class:     com_govee_pad_base_lua_LuaState
 * Method:    nativeOpenlibs
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_govee_pad_base_lua_LuaState_nativeOpenlibs
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_govee_pad_base_lua_LuaState
 * Method:    nativeDofile
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_govee_pad_base_lua_LuaState_nativeDofile
        (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_govee_pad_base_lua_LuaState
 * Method:    nativeDoString
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_govee_pad_base_lua_LuaState_nativeDoString
        (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_govee_pad_base_lua_LuaState
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_govee_pad_base_lua_LuaState_nativeClose
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_govee_pad_base_lua_LuaState
 * Method:    nativeGetTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_govee_pad_base_lua_LuaState_nativeGetTop
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_govee_pad_base_lua_LuaState
 * Method:    nativeTostring
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_govee_pad_base_lua_LuaState_nativeTostring
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_govee_pad_base_lua_LuaState
 * Method:    nativeTonumber
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_com_govee_pad_base_lua_LuaState_nativeTonumber
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_govee_pad_base_lua_LuaState
 * Method:    nativeType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_govee_pad_base_lua_LuaState_nativeType
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_govee_pad_base_lua_LuaState
 * Method:    nativeTypename
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_govee_pad_base_lua_LuaState_nativeTypename
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_govee_pad_base_lua_LuaState
 * Method:    nativeGetglobal
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_govee_pad_base_lua_LuaState_nativeGetglobal
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_govee_pad_base_lua_LuaState
 * Method:    nativePushString
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_govee_pad_base_lua_LuaState_nativePushString
(JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_govee_pad_base_lua_LuaState
 * Method:    nativeCall
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_govee_pad_base_lua_LuaState_nativeCall
(JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_govee_pad_base_lua_LuaState
 * Method:    nativePcall
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_com_govee_pad_base_lua_LuaState_nativePcall
(JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_govee_pad_base_lua_LuaState
 * Method:    nativePop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_govee_pad_base_lua_LuaState_nativePop
(JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
